In [ ]:
# Используем библиотеку NumPy
import numpy as np

# Примеры создания массивов

In [45]:
# Массив из обычных списков
list_data = [1,2,3,4,5]
arr_list = np.array(list_data)
print("Одномерный массив:\n", arr_list)

# Двумерный массив из вложенных списков
matrix_data = [[1,2,3],[4,5,6],[7,8,9], [10,11,12]]
arr_matrix = np.array(matrix_data)
print("Двумерный массив:\n", arr_matrix)

Одномерный массив:
 [1 2 3 4 5]
Двумерный массив:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# С помощью функции zeros()
arr_zero = np.zeros((2,3))
print("Двумерный массив из нулей:\n", arr_zero) 

# С помощью функции ones()
arr_one = np.ones((2,3,4)) # трактуется как 2 двумерные единичные матрицы размера 3 на 4
print("Трехмерный массив из единиц:\n", arr_one)

# С помощью функции eye()
arr_eye = np.eye(4)
print("Единичная матрица 4x4:\n", arr_eye)

# С помощью функции arage()
arr = np.arange(10, 11, 0.13, dtype=float) # от 10 до 11 (не включая) с шагом 0.13
print("Последовательность вещественных чисел:\n", arr)

# С помощью функции linspace()
linspace_array = np.linspace(0, 1, 5) # 5 чисел от 0 до 1
print("Массив линейного распределения:\n", linspace_array)


Двумерный массив из нулей:
 [[0. 0. 0.]
 [0. 0. 0.]]
Трехмерный массив из единиц:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Единичная матрица 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Последовательность вещественных чисел:
 [10.   10.13 10.26 10.39 10.52 10.65 10.78 10.91]
Массив линейного распределения:
 [0.   0.25 0.5  0.75 1.  ]


# Демонстрация атрибутов

In [54]:
print(f"Для двумерной матрицы arr_matrix:\n Форма: {arr_matrix.shape}\n Тип данных: {arr_matrix.dtype}")

print(f"Для последовательности вещественных чисел arr:\n Форма: {arr.shape}\n Тип данных: {arr.dtype}")

Для двумерной матрицы arr_matrix:
 Форма: (4, 3)
 Тип данных: int32
Для последовательности вещественных чисел arr:
 Форма: (8,)
 Тип данных: float64


# Индексация и срезы

In [55]:
print("Исходный массив:", arr_list)

# Получение отдельного элемента
print("arr_list[2] =", arr_list[2])  # третий элемент

# Извлечение подмассива с помощью среза
print("arr_list[1:4] =", arr_list[1:4])  # элементы с индексами 1, 2, 3
print("arr_list[::2] =", arr_list[::2])  # каждый второй элемент

# Индексирование в двумерном массиве
print("Двумерная матрица:\n", arr_matrix)

print("arr_matrix[1, 2] =", arr_matrix[1, 2])  # элемент во второй строке, третьем столбце
print("arr_matrix[0] =", arr_matrix[0])        # первая строка
print("arr_matrix[:, 1] =", arr_matrix[:, 1])  # второй столбец
print("Срез arr_matrix[0:2, 1:3]:\n", arr_matrix[0:2, 1:3]) # подматрица 2x2


Исходный массив: [1 2 3 4 5]
arr_list[2] = 3
arr_list[1:4] = [2 3 4]
arr_list[::2] = [1 3 5]
Двумерная матрица:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
arr_matrix[1, 2] = 6
arr_matrix[0] = [1 2 3]
arr_matrix[:, 1] = [ 2  5  8 11]
Срез arr_matrix[0:2, 1:3]:
 [[2 3]
 [5 6]]


# Векторные операции и статистика

In [56]:
# Создание двух массивов для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Массив a:", a)
print("Массив b:", b)

# Поэлементное сложение массивов
sum_result = a + b
print("a + b =", sum_result)

# Поэлементное умножение массивов
mult_result = a * b
print("a * b =", mult_result)

# Операции с константой
print("a + 10 =", a + 10)
print("b * 2 =", b * 2)

# Базовые статистические операции
print("\nСтатистика для массива a:", a)
print("Среднее значение:", np.mean(a))
print("Сумма всех элементов:", np.sum(a))
print("Минимальное значение:", np.min(a))
print("Максимальное значение:", np.max(a))
print("Стандартное отклонение:", np.std(a))

# Статистика по осям в двумерном массиве
print("\nСтатистика для матрицы:")
print(arr_matrix)
print("Среднее по столбцам:", np.mean(arr_matrix, axis=0))
print("Сумма по строкам:", np.sum(arr_matrix, axis=1))

Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
a + b = [ 6  8 10 12]
a * b = [ 5 12 21 32]
a + 10 = [11 12 13 14]
b * 2 = [10 12 14 16]

Статистика для массива a: [1 2 3 4]
Среднее значение: 2.5
Сумма всех элементов: 10
Минимальное значение: 1
Максимальное значение: 4
Стандартное отклонение: 1.118033988749895

Статистика для матрицы:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Среднее по столбцам: [5.5 6.5 7.5]
Сумма по строкам: [ 6 15 24 33]
